### ISSUE TITLE
Compiler integration with the Project Explorer (& Task Providers)

### ISSUE THREAD

**Issue by joelday** [joelday/papyrus-lang#23]
- Brings back @shad0wshayd3's hard work
- Automatic task discovery/configuration based on found .ppj files
- Tasks (contributed or configured) can be authored in tasks.json and resolved by the TaskProvider to configure execution.

Blocked by https://github.com/Microsoft/vscode/issues/33523

**Comment by joelday** [comment]
Can be done after https://github.com/Microsoft/vscode/pull/71027

**Comment by joelday** [comment]
Working branch: https://github.com/joelday/papyrus-lang/tree/task-provider

**Comment by minkir014** [comment]
Close this issue as it solved.

**Comment by Scrivener07** [comment]
If I recall correctly, you mentioned this will likely use the "Project Explorer" instead of the VS Code Task system. Ill tag this with the project explorer label so it shows up under that filter.

**Comment by Scrivener07** [comment]
Some context on where the tasks thing went.

Here's an example task provider: https://github.com/microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/extension.ts


Problem is, if you add a custom task, like "type": "papyrus", you can't just add a bunch of custom configuration values to that. You must have a provider that provides specific tasks, and there has to be one that matches it.

https://github.com/microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/extension.ts#L30
That never even gets called because it's not actually supported yet.

What we can do, though, is have a task schema that has an optional `projectPath`, where if it is missing, it just uses your CK `.ini` settings. 
Then our provider would just search for all `.ppj` files. One benefit here would be, you could compile without even adding a `tasks.json`, you just pick it out of the command palette.

My thinking would be to just have the provider produce tasks for each combination of the (asm/debug/etc.) settings if you want to override.

**Comment by rjstone** [comment]
This is now done. We now autodiscover build tasks for .PPJ files (as soon as the PR I submitted with that fix gets merged, hint hint)
