### ISSUE TITLE
Configuration and workflow for developers using mod managers/symbolic links

### ISSUE THREAD

**Issue by Deadmano** [joelday/papyrus-lang#38]
I have Skyrim (Legendary Edition) installed to one drive, but I used a symbolic link to move it to my SSD. The automatic detection picks up the install correctly on the drive it was originally installed to, but the extension doesn't work nor does it log any errors. If I manually change the "papyrus.skyrim.installPath" value to the SSD path, it then works.

**Comment by Scrivener07** [comment]
Deadmano is using Mod Organizer if I followed that right. MO enforces a highly unconventional setup using symbolic links. The actual game installation directory is intended to remain completely vanilla. Then the MO manager will "patch" in additional directories and files using the symbolic links to form a sort of final virtual directory. This is a pretty genius management strategy for end users but it is sub-par for developers in my opinion, which is one of the main reasons I prefer not to use it. Once you start symbolic linking all game files then you also need to start going down the rabbit hole of executing all tools you need through MO so that they can find these unconventional directory locations. Unfortunately this management strategy has taken a strong hold in the community with the two most popular mod managers these days imposing it (Vortex and Mod Organizer). So last thoughts on that, its a totally valid management strategy but not without its own challenges.

#### See Also
* [Mod Organizer Guide](https://wiki.step-project.com/Guide:Mod_Organizer)
* [MO - The Virtual Filing System (VFS)](https://wiki.step-project.com/Guide:Mod_Organizer_Advanced#The_virtual_filing_system)

#### Ye Olde Managers
This is in contrast to how the Wrye Bash (BAIN) and NMM (FOMOD) mod managers work. These use a completely conventional management strategy by moving installed files into the games installation directory. This strategy works as expected for various tools and applications.

#### Final Thoughts
Even though managers using a visualized file system via symbolic links have gain massive popularity among mod users over the last 5 or so years there is still what I perceive to be a significant portion of the *author / developer* community that have stuck with the more conventional managers to avoid these challenges. So a big part of deciding a solution will be considering the target audience. In my opinion of course.

**Comment by Scrivener07** [comment]
Well Ive been out of the Skyrim loop for a while now. MO is legacy now. [MO2](https://github.com/ModOrganizer2/modorganizer) is the successor. Both projects were started by TanninOne but he has moved on to create [Vortex](https://www.nexusmods.com/about/vortex/) after being hired by the NexusMods.com website. MO2 is still actively developed by the community.

For some bonus trivia, [Nexus Mod Manager](https://github.com/Nexus-Mods/Nexus-Mod-Manager) (NMM) has a similar history starting with the author Timeslip's [OBMM](https://www.nexusmods.com/oblivion/mods/2097), to [FOMM](https://github.com/foesmm/fomm), and eventually NMM. All of these projects are still actively developed in some capacity. This is some good stuff to be aware of when searching the web and weeding through legacy information.

**Comment by Qudix** [comment]
I don't believe Symbolic Links are the correct term to use when referring to Mod Organizer's Virtual File System (USVFS). It creates "links" in memory, but they don't actually exist outside of the process launched by MO. The links you posted even confirm this.

**Comment by minkir014** [comment]
Did it work with MO2 and these projects or no? I mean the projects mentioned by https://github.com/Scrivener07

**Comment by Deadmano** [comment]
> 
> 
> I don't believe Symbolic Links are the correct term to use when referring to Mod Organizer 2's Virtual File System (USVFS). It creates "links" in memory, but they don't actually exist outside of the process launched by MO2. The links you posted even confirm this.
> 
> [The Github repository explains in more detail](https://github.com/TanninOne/usvfs)
I wasn't referring to MO using symbolic links, at all, as it doesn't. I was referring to my specific case where I am working with script files outside of the game directory, and the game directory itself is a symbolic link, move from my HDD to SSD for performance reasons. The issue comes with this extension not really allowing for us to work on our scripts outside of the game directory, as some of us like to keep a clean development environment whilst developing.

**Comment by minkir014** [comment]
What is the problem with setting the path to ssd? If it works.

**Comment by joelday** [comment]
Since there's a workaround and we haven't encountered similar issues, let's just reopen this later if it comes up again.

**Comment by ogrotten** [comment]
First of all: 
>Since there's a workaround and we haven't encountered similar issues, let's just reopen this later if it comes up again.

@joelday What's the workaround mentioned here?

> The issue comes with this extension not really allowing for us to work on our scripts outside of the game directory, as some of us like to keep a clean development environment whilst developing.

Yes yes.

I have a couple of personal mods that I work on continually. I keep their scripts separated in different MO2 mods. Since this extension only parses for symbols etc via the SkyrimEditorPrefs.ini my are not seen. Further, VSCode does not accept a skyrim virtual directory structure when started from within MO2

It seems that the solution would be one of these:
- allow the user to configure their own script source directories
- use Workspace directories
- use USVFS to coerce the compiler into believing that the script it's looking at is indeed in /Data/Scripts/Source
